:memo: Update documentation

diff --git a/scripts/r_flatheme b/scripts/r_flatheme
--- a/scripts/r_flatheme
+++ b/scripts/r_flatheme
@@ -11,25 +11,24 @@
 # |_______| |_______|
 # 
 #
-COMMAND_NAME="r_flatheme"
 
 ############################################################
 # Help                                                     #
 ############################################################
-Help()
-{
-   # Display Help
-   echo
-   echo "Usage: $COMMAND_NAME [OPTIONS]"
-   echo
-   echo "Set the GTK Theme for Flatpak on KDE Plasma."
-   echo
-   echo "Options:"
-   echo "  -h     Print this Help."
-   echo "  -s     Set the GTK theme."
-   echo "  -u     Unset the GTK theme."
-   echo
+Help() {
+  cat << EOF
+Usage: $(basename $0) [OPTIONS]
+
+Set the GTK Theme for Flatpak on KDE Plasma.
+
+OPTIONS:
+  -h     Display this help message
+  -s     Set the GTK theme for Flatpak.
+  -u     Unset the GTK theme for Flatpak.
+EOF
+  exit 1
 }
+
 
 ############################################################
 # SetGTK                                                   #
@@ -43,9 +42,7 @@ SetGTK()
       mkdir -p $confdir
       cp $HOME/.config/gtk-3.0/settings.ini $confdir/settings.ini
    done
-   echo 
-   echo "setting gtk theme... done!"
-   echo
+   echo -e "\nsetting gtk theme... done!\n"
 }
 
 ############################################################
@@ -59,9 +56,7 @@ UnsetGTK()
       confdir="${dir}config/gtk-3.0"
       rm -rf $confdir/settings.ini
    done
-   echo 
-   echo "unsetting gtk theme... done!"
-   echo 
+   echo -e "\nunsetting gtk theme... done!\n"
 }
 
 ############################################################
@@ -70,10 +65,8 @@ UnsetGTK()
 InvalidOption()
 {
    # Display Invalid Option Text
-   echo
-   echo "$COMMAND_NAME: invalid option."
-   echo "See '$COMMAND_NAME -h'"
-   echo
+   echo -e "$COMMAND_NAME: invalid option.\n"
+   Help
 }
 
 ############################################################
diff --git a/scripts/r_img_rename b/scripts/r_img_rename
--- a/scripts/r_img_rename
+++ b/scripts/r_img_rename
@@ -14,26 +14,33 @@
 #
 
 # Define function to display usage information.
-function show_usage {
-  echo "Usage: $0 -i|--imagepath <path> -s|--string <string> [-p|--position <before|after>] [-h|--help]"
-  echo ""
-  echo "Description:"
-  echo "  This script adds a given string to the filenames of all image files"
-  echo "  (i.e., files with the extensions 'jpg', 'jpeg', 'png', 'gif', and 'bmp')"
-  echo "  within a specified folder."
-  echo ""
-  echo "Options:"
-  echo "  -i, --imagepath <path>    The path to the folder containing the image files."
-  echo "  -s, --string <string>     The string to add to the filenames."
-  echo "  -p, --position <before|after>"
-  echo "                            The position at which to add the string. Must be"
-  echo "                            'before' or 'after'. Default is 'before'."
-  echo "  -h, --help                Show usage information."
-  exit 1
+Help() {
+  cat <<-EOF
+Usage: $0 -i PATH -s STRING [-p <prefix|suffix>] [-h]
+
+This script adds a given string to the file names of all image files in a folder.
+Supported image types are: 'jpg', 'jpeg', 'png', 'gif', and 'bmp'
+
+OPTIONS:
+  -h                  Display this help message
+  -i PATH             The path to the folder containing the image files.
+  -s STRING           The string to add to the filenames.
+  -p <prefix|suffix>  The position at which to add the string. Must be 'prefix' or 'suffix'. Default is 'prefix'.
+
+EXAMPLES:
+  $(basename $0) -i . -s new_
+   All image files in the current directory will be prefixed with the string "new_".
+   For example, if there is an image file called image.jpg in the current directory, the script will rename it to new_image.jpg.
+
+  $(basename $0) -i . -p suffix -s _new
+   All image files in the current directory will be suffixed with the string "_new". 
+   For example, if there is an image file called image.jpg in the current directory, the script will rename it to image_new.jpg.
+EOF
 }
 
+
 # Set default values.
-position="before"
+position="prefix"
 
 # Parse command-line arguments.
 while [[ $# -gt 0 ]]; do
@@ -52,18 +59,20 @@ while [[ $# -gt 0 ]]; do
       shift 2
       ;;
     -h|--help)
-      show_usage
+      Help
+      exit 1
       ;;
     *)
-      show_usage
+      Help
+      exit 1
       ;;
   esac
 done
 
 # Check if required arguments were passed.
 if [ -z "$imagepath" ] || [ -z "$string" ]; then
-  echo "Error: Missing required argument(s)."
-  show_usage
+  echo -e "Error: Missing required argument(s).\n"
+  Help
 fi
 
 # Loop through all image files in the folder.
@@ -74,13 +83,13 @@ for file in $imagepath/*.{jpg,jpeg,png,gif,bmp}; do
     filename=$(basename "$file")
     extension="${filename##*.}"
 
-    # Add the string before or after the filename, depending on the position.
-    if [ "$position" = "before" ]; then
-      newname="${string}-${filename}"
-    elif [ "$position" = "after" ]; then
-      newname="${filename%.*}-${string}.${extension}"
+    # Add the string prefix or suffix the filename, depending on the position.
+    if [ "$position" = "prefix" ]; then
+      newname="${string}${filename}"
+    elif [ "$position" = "suffix" ]; then
+      newname="${filename%.*}${string}.${extension}"
     else
-      echo "Error: Invalid 'position' argument. Must be 'before' or 'after'."
+      echo "Error: Invalid 'position' argument. Must be 'prefix' or 'suffix'."
       exit 1
     fi
 
diff --git a/scripts/r_pdf_optimize b/scripts/r_pdf_optimize
--- a/scripts/r_pdf_optimize
+++ b/scripts/r_pdf_optimize
@@ -13,11 +13,54 @@
 # Requirementes:
 # ->  gs
 
+
+# # Optimize all PDF files on current directory Using eBook settings
+
+# command -v gs >/dev/null 2>&1 || { echo >&2 "I require gs but it's not installed. Aborting."; exit 1; }
+
+# shopt -s nullglob # Sets nullglob
+# shopt -s nocaseglob # Sets nocaseglob
+# for f in *.pdf; do
+#   gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 \
+#   -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH \
+#   -sOutputFile="${f%.*}-optimized.pdf" "$f"
+# done
+
+
+#!/bin/bash
+
+Help() {
+  cat <<EOF
+Usage: optimize-pdf [OPTION]
+
+Optimizes all PDF files in the current directory using ebook settings.
+
+OPTIONS:
+  -h  Print this help message.
+EOF
+}
+
+# Display Help if -h option is passed
+if [[ $1 == "-h" ]]; then
+  Help
+  exit 0
+fi
+
+# Check if gs is installed
 command -v gs >/dev/null 2>&1 || { echo >&2 "I require gs but it's not installed. Aborting."; exit 1; }
 
+# Check if there are PDF files in the current directory
 shopt -s nullglob # Sets nullglob
 shopt -s nocaseglob # Sets nocaseglob
-for f in *.pdf; do
+pdf_files=(*.pdf)
+if (( ${#pdf_files[@]} == 0 )); then
+  echo -e "No PDF files found in the current directory.\n"
+  Help
+  exit 1
+fi
+
+# Optimize PDF files using ebook settings
+for f in "${pdf_files[@]}"; do
   gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 \
   -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH \
   -sOutputFile="${f%.*}-optimized.pdf" "$f"
diff --git a/scripts/r_svgcleaner b/scripts/r_svgcleaner
--- a/scripts/r_svgcleaner
+++ b/scripts/r_svgcleaner
@@ -17,32 +17,61 @@ command -v tidy >/dev/null 2>&1 || { echo >&2 "I require tidy but it's not insta
 command -v inkscape >/dev/null 2>&1 || { echo >&2 "I require inkscape but it's not installed. Aborting."; exit 1; }
 
 # Define a function to display help information
-function display_help {
-    echo "Usage: $(basename "$0") [FILE]"
-    echo "  -h              Display this help message"
-    echo "  FILE            SVG file to process, or '.' to process all SVG files in the current directory"
+Help() {
+    cat << EOF
+Usage: $(basename "$0") [OPTIONS] [FILE]
+
+SVG batch processing script with svgcleaner, tidy, and inkscape
+
+OPTIONS:
+  -h     Display this help message
+  -p     Generate PNG versions of the processed SVG files
+
+ARGUMENTS:
+  FILE   SVG file to process, or '.' to process all SVG files in the current directory
+
+EXAMPLES:
+  $(basename $0) .
+    Process all SVG files in the current directory.
+
+  $(basename $0) icon.svg
+    Process the 'icon.svg' file in the current directory.
+
+  $(basename $0) -p icon.svg
+    Process the 'icon.svg' file in the current directory and generate a PNG version of the processed file.
+EOF
 }
 
 
+
+
 # Define a function to process an SVG icon
-function process_icon (){
+function process_icon {
     ICON=$1
     #echo "process the icon ${ICON}"
     svgcleaner "$ICON" "$ICON"
     tidy -q -xml -indent -wrap 0 -m "$ICON"
-    inkscape --export-filename "${ICON%.*}.png" --export-area-page "$ICON"
+    if [ $GENERATE_PNG -eq 1 ]
+    then
+        inkscape --export-filename "${ICON%.*}.png" --export-area-page "$ICON"
+    fi
 }
 
-# Use getopts to handle the '-h' flag
-while getopts "h" option; do
+GENERATE_PNG=0
+
+# Use getopts to handle the '-h' and '-p' flags
+while getopts "hp" option; do
     case $option in
         h)
-            display_help
+            Help
             exit
             ;;
+        p)
+            GENERATE_PNG=1
+            ;;
         \?)
-            echo "Invalid option: -$OPTARG" >&2
-            display_help
+            echo -e "Invalid option: -$OPTARG\n" >&2
+            Help
             exit 1
             ;;
     esac
@@ -59,8 +88,7 @@ shopt -s nocaseglob # Sets nocaseglob
 # Check if the script is called without arguments
 if [ $# -eq 0 ]
 then
-    echo "No arguments supplied"
-    display_help
+    Help
     exit 1
 else
     file=$1
@@ -81,7 +109,8 @@ else
                 process_icon $file
             else
                 echo "File \"${file}\" doesn't exist or is not a valid SVG file!"
-                display_help
+                echo
+                Help
                 exit 1
             fi
             exit;
