:memo: Add help

diff --git a/scripts/r_svgcleaner b/scripts/r_svgcleaner
--- a/scripts/r_svgcleaner
+++ b/scripts/r_svgcleaner
@@ -15,6 +15,28 @@
 # ->  tidy [ http://www.html-tidy.org/developer ]
 # ->  inkscape - Optional for exporting PNG file
 
+function display_help {
+    echo "Usage: $(basename "$0") [FILE]"
+    echo "  -h              Display this help message"
+    echo "  FILE            SVG file to process, or '.' to process all SVG files in the current directory"
+}
+
+while getopts "h" option; do
+    case $option in
+        h)
+            display_help
+            exit
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            display_help
+            exit 1
+            ;;
+    esac
+done
+
+shift $((OPTIND-1))
+
 command -v svgcleaner >/dev/null 2>&1 || { echo >&2 "I require svgcleaner but it's not installed. Aborting."; exit 1; }
 command -v tidy >/dev/null 2>&1 || { echo >&2 "I require tidy but it's not installed. Aborting."; exit 1; }
 command -v inkscape >/dev/null 2>&1 || { echo >&2 "I require inkscape but it's not installed. Aborting."; exit 1; }
@@ -30,36 +52,34 @@ function process_icon (){
     inkscape --export-filename "${ICON%.*}.png" --export-area-page "$ICON"
 }
 
-
 if [ $# -eq 0 ]
-    then
-        echo "No arguments supplied"
-    else
-        file=$1
-        case $file in
-            # ALL FILES IN FOLDER
-            .)
-            #
+then
+    echo "No arguments supplied"
+    display_help
+    exit 1
+else
+    file=$1
+    case $file in
+        # ALL FILES IN FOLDER
+        .)
             for icon in *.svg
             do
                 process_icon $icon
             done
             exit;
             ;;
-            # DEFAULT -  ONE SPECIFIC FILE
-            *)
-            # Cheking if file exists and is a valid file
+        # DEFAULT -  ONE SPECIFIC FILE
+        *)
+            # Checking if file exists and is a valid file
             if [ -f $file ] && [ "${file: -4}" == ".svg" ]; then
                 # File is exist and is allowed
                 process_icon $file
             else
                 echo "File \"${file}\" doesn't exist or is not a valid SVG file!"
+                display_help
+                exit 1
             fi
             exit;
             ;;
-        esac
-
+    esac
 fi
-
-
-
